### ISSUE TITLE
Access system resources and dev workflow

### ISSUE THREAD

**Issue by colinbes** [nwutils/nw-vue-cli-example#3]
It seems to be a “standard” solution while developing to run vue’s serve service and then run nw with main set to localhost:port. While this is convenient it doesn’t work when your nw app is accessing system resources (example, file system access). One way around this is to create more complicated build setup (not too bad) and implement watch to build on file change and then have nw run on built files.

Add typescript and it gets more complicated quickly.

This template is a great start to nwjs/vue and was looking for advice on workflow/setup when accessing browser restricted resources - would be neat addition to this project,

**Comment by TheJaredWilcurt** [comment]
This approach works fine for Node access (`process`, `require`, etc.). You just need to access them through:

* Either `window.nw.process` or `window.process`
* Either `window.nw.require` or `window.require`

This is due to the way Vue's template compiler understands globals and imports. It requires you to reference `window.` to inform it that it is a global.

I have updated the repo to `v1.1.0` which includes a File System example component.

TypeScript is an additional abstraction layer on top of many existing abstraction layers, it will always add additional complexity. It should work the same as it does in the normal Vue-CLI however. The only additional work you would need to do is potentially define `window.nw` as "Any".

You can look at this "How to setup Angular + NW.js" tutorial to see how TS is handled:

* https://dev.to/thejaredwilcurt/angular-cli-and-nwjs-for-development-49gl#step-3-adding-in-nwjs

I do not intend on adding in Vue-Router, Vuex, Typescript, etc into this boilerplate, as those will not be needed by all users, and should be relatively simple to set up for those familiar with those technologies and Vue-CLI.

**Comment by colinbes** [comment]
I agree that TypeScript should not be in base template but I suspect that's where my issue is as if I rename my encryption.ts to encryption.js then I can get it all working - I will try suggestion of defining angular.nw

**Comment by TheJaredWilcurt** [comment]
This is how the polyfill is setup in nw-angular-cli-example:

* https://github.com/nwutils/nw-angular-cli-example/blob/master/src/polyfills.ts#L62

**Comment by colinbes** [comment]
Got that part working. Thanks for your guidance.
